# Generated by Django 5.2.1 on 2025-05-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_pais', models.CharField(max_length=2)),
                ('codigo_api', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_api', models.CharField(max_length=20, unique=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='analisis.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local_ht', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante_ht', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_local_ft', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante_ft', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resultado_1x2', models.CharField(blank=True, choices=[('1', 'Local'), ('X', 'Empate'), ('2', 'Visitante')], max_length=2, null=True)),
                ('over_1_5', models.BooleanField(null=True)),
                ('over_2_5', models.BooleanField(null=True)),
                ('btts', models.BooleanField(null=True)),
                ('marco_local', models.BooleanField(null=True)),
                ('marco_visitante', models.BooleanField(null=True)),
                ('over_1_5_local', models.BooleanField(null=True)),
                ('codigo_api', models.CharField(max_length=30, unique=True)),
                ('equipo_local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_local', to='analisis.equipo')),
                ('equipo_visitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visitante', to='analisis.equipo')),
                ('liga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis.liga')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personalizado', models.CharField(max_length=200)),
                ('equipo_destacado', models.CharField(choices=[('local', 'Local'), ('visitante', 'Visitante'), ('ninguno', 'Ninguno')], default='ninguno', max_length=10)),
                ('cuota_estim_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuota_casa_apuestas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('NO', 'No Apuesta'), ('LIVE', 'Live'), ('APOSTADO', 'Apostado')], default='NO', max_length=20)),
                ('resultado', models.CharField(choices=[('sin resultado', 'Sin resultado'), ('acierto', 'Acierto'), ('fallo', 'Fallo')], default='sin resultado', max_length=20)),
                ('favorito', models.BooleanField(default=False)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='analisis.metodoanalisis')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.partido')),
            ],
        ),
        migrations.CreateModel(
            name='RachaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('gol_ht', 'Gol HT'), ('tts', 'Marcar Gol'), ('over_1_5', 'Over 1.5'), ('over_2_5', 'Over 2.5'), ('over_1_5_local', 'Over 1.5 Local'), ('ganar', 'Ganar')], max_length=20)),
                ('contexto', models.CharField(choices=[('local', 'Jugando de local'), ('visitante', 'Jugando de visitante'), ('ambos', 'Combinado')], max_length=10)),
                ('tipo', models.CharField(choices=[('actual', 'Actual'), ('historica', 'Histórica')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('temporada', models.CharField(max_length=9)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rachas', to='analisis.equipo')),
            ],
            options={
                'unique_together': {('equipo', 'condicion', 'contexto', 'tipo', 'temporada')},
            },
        ),
    ]
