# Generated by Django 5.2.1 on 2025-05-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='codigo_pais',
            field=models.CharField(max_length=6),
        ),
    ]
