# Generated by Django 5.2.1 on 2025-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_alter_liga_codigo_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='codigo_api',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
