# Generated by Django 5.2.1 on 2025-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_alter_liga_codigo_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_api',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='codigo_api',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
