# Generated by Django 5.2.1 on 2025-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_alter_equipo_codigo_api_alter_partido_codigo_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachaequipo',
            name='temporada',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
