# Generated by Django 5.2.1 on 2025-05-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_alter_rachaequipo_temporada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidoanalisis',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='partidoanalisis',
            name='nombre_personalizado',
        ),
        migrations.RemoveField(
            model_name='partidoanalisis',
            name='resultado',
        ),
    ]
