# Generated by Django 5.2.1 on 2025-05-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_remove_partidoanalisis_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidoanalisis',
            name='equipo_destacado',
        ),
    ]
