# Generated by Django 5.2.1 on 2025-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0007_remove_partidoanalisis_equipo_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoanalisis',
            name='porcentaje_acierto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='partidoanalisis',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
