# Generated by Django 5.2.1 on 2025-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0008_partidoanalisis_porcentaje_acierto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='gol_ht',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
