# Generated by Django 5.2.1 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0009_partido_gol_ht'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoanalisis',
            name='equipo_destacado',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('visitante', 'Visitante')], max_length=10, null=True),
        ),
    ]
