# Generated by Django 5.2.1 on 2025-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0011_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachaequipo',
            name='condicion',
            field=models.CharField(choices=[('gol_ht', 'Gol HT'), ('tts', 'Marcar Gol'), ('btts', 'Ambos Marcan'), ('over_1_5', 'Over 1.5'), ('over_2_5', 'Over 2.5'), ('over_1_5_marcados', 'Over 1.5 Marcados'), ('over_1_5_recibidos', 'Over 1.5 Recibidos'), ('ganar', 'Ganar')], max_length=30),
        ),
    ]
