# Generated by Django 5.2.1 on 2025-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0012_alter_rachaequipo_condicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='liga',
        ),
        migrations.AddField(
            model_name='equipo',
            name='ligas',
            field=models.ManyToManyField(related_name='equipos', to='analisis.liga'),
        ),
    ]
