# Generated by Django 5.2.1 on 2025-06-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0013_remove_equipo_liga_equipo_ligas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rachaequipo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rachaequipo',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analisis.liga'),
        ),
        migrations.AlterUniqueTogether(
            name='rachaequipo',
            unique_together={('equipo', 'condicion', 'contexto', 'tipo', 'temporada', 'liga')},
        ),
    ]
