# Generated by Django 5.2.1 on 2025-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0014_alter_rachaequipo_unique_together_rachaequipo_liga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoanalisis',
            name='cuota_casa_apuestas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
