# Generated by Django 5.2.1 on 2025-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0015_alter_partidoanalisis_cuota_casa_apuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidoanalisis',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
