# Generated by Django 5.2.1 on 2025-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0016_alter_partidoanalisis_valor_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='codigo_iso_pais',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='liga',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
