# Generated by Django 5.2.1 on 2025-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0017_liga_codigo_iso_pais_liga_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='codigo_iso_pais',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
