# Generated by Django 5.2.1 on 2025-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0018_alter_liga_codigo_iso_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
