# Generated by Django 5.2.1 on 2025-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.CharField(choices=[('prueba', 'Prueba gratuita'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20),
        ),
    ]
